# Generated by Django 3.2.3 on 2021-05-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atracao',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='atracoes'),
        ),
    ]
